version: v1.1.0

dsn: '##kratos_dsn##'

serve:
  public:
    base_url: '##serve_public_base_url##'
    cors:
      enabled: ##serve_public_cors_enabled##
      allowed_origins: @@serve_public_cors_allowed_origins@@
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: '##serve_admin_base_url##'

selfservice:
  default_browser_return_url: '##selfservice_default_browser_return_url##'
  allowed_return_urls: @@selfservice_allowed_return_urls@@

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: true
        identifier_similarity_check_enabled: true
        ignore_network_errors: true
        max_breaches: 1
        min_password_length: 8
    profile:
      enabled: true
    totp:
      config:
        issuer: Ticketing
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
      config:
        lifespan: 15m
        base_url: ''
    code:
      enabled: true

  flows:
    error:
      ui_url: '##selfservice_flows_errors_ui_url##'

    settings:
      ui_url: '##selfservice_flows_settings_ui_url##'
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: '##selfservice_flows_recovery_ui_url##'
      use: code
      lifespan: 15m
      notify_unknown_recipients: false

    verification:
      enabled: true
      ui_url: '##selfservice_flows_verification_ui_url##'
      use: code
      after:
        default_browser_return_url: '##selfservice_default_browser_return_url##'

    logout:
      after:
        default_browser_return_url: '##selfservice_default_browser_return_url##'

    login:
      ui_url: '##selfservice_flows_login_ui_url##'
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                method: '##selfservice_flows_login_after_hook_config_method##'
                auth:
                  type: api_key
                  config:
                    value: '##selfservice_flows_login_after_hook_config_auth_config_value##'
                    in: header
                    name: X-Ory-API-Key
                url: '##selfservice_flows_login_after_hook_config_url##'
                body: '##selfservice_flows_login_after_hook_config_body##'
                can_interrupt: ##selfservice_flows_login_after_hook_config_can_interrupt##
                response:
                  ignore: ##selfservice_flows_login_after_hook_config_response_ignore##
                  parse: ##selfservice_flows_login_after_hook_config_response_parse##

    registration:
      lifespan: 10m
      ui_url: '##selfservice_flows_ui_base_url##/registration'
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                method: '##selfservice_flows_registration_after_hook_config_method##'
                auth:
                  type: api_key
                  config:
                    value: '##selfservice_flows_registration_after_hook_config_auth_config_value##'
                    in: header
                    name: X-Ory-API-Key
                url: '##selfservice_flows_registration_after_hook_config_url##'
                body: '##selfservice_flows_registration_after_hook_config_body##'
                can_interrupt: ##selfservice_flows_registration_after_hook_config_can_interrupt##
                response:
                  ignore: ##selfservice_flows_registration_after_hook_config_response_ignore##
                  parse: ##selfservice_flows_registration_after_hook_config_response_parse##
            - hook: show_verification_ui

log:
  level: '##log_level##'
  format: json
  leak_sensitive_values: true

secrets:
  cookie:
    - '##secrets_cookie##'
  cipher:
    - '##secrets_cipher##'

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: '##identity_schemas_default##'

courier:
  smtp:
    from_name: '##courier_smtp_from_name##'
    connection_uri: '##courier_smtp_connection_uri##'

feature_flags:
  cacheable_sessions: false
  # use_continue_with_transitions: true

oauth2_provider:
  url: '##oauth2_provider_url##'
