apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: 'development'
  PROXY_SERVER_URLS: 'http://ticketing.dev'
  FRONTEND_URL: 'http://ticketing.dev'
  MAX_PAYLOAD_SIZE: '5'
  SWAGGER_PATH: open-api
  ASYNC_API_PATH: async-api
  HEAP_USED_TRESHOLD: '1073741824'
  MEMORY_RSS_TRESHOLD: '3221225472'
  DISK_STORAGE_TRESHOLD: '536870912000'
  JWT_ALGORITHM: ES256
  JWT_EXPIRES_IN: 60m
  JWT_ISSUER: ticketing.dev
  RMQ_URL: http://rmq-srv:5672
  ORY_BASE_PATH: http://localhost:4000
  LOG_LEVEL: info
