apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      restartPolicy: Always
      containers:
        - name: auth
          image: ghcr.io/getlarge/ticketing-auth
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: PORT
              value: '3000'
            - name: SERVER_URL
              value: 'https://ticketing.dev'              
            - name: MONGODB_URI
              value: mongodb://auth-mongo-srv:27017/auth
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PUBLIC_KEY
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: SESSION_KEY
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
