apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      restartPolicy: Always
      containers:
        - name: expiration
          image: ghcr.io/getlarge/ticketing-expiration
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: PORT
              value: '3000'
            - name: SERVER_URL
              value: 'https://ticketing.dev'
            - name: REDIS_URL
              value: redis://expiration-redis-srv:6379
          startupProbe:
            exec:
              command: ['pgrep', '-x', 'node']
            failureThreshold: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 2              
          resources:
            limits:
              memory: '128Mi'
              cpu: '150m'
