apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      restartPolicy: Always
      containers:
        - name: payments
          image: ghcr.io/getlarge/ticketing-payments
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: PORT
              value: '3000'
            - name: SERVER_URL
              value: 'https://ticketing.dev'
            - name: MONGODB_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_PUBLIC_KEY
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: SESSION_KEY
          resources:
            limits:
              memory: '128Mi'
              cpu: '150m'
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
