apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: apps
deploy:
  kubectl:
    manifests:
      - './infra/k8s/apps/*'
build:
  local:
    push: false
    concurrency: 3
  artifacts:
    # AUTH
    - image: ghcr.io/getlarge/ticketing-auth
      context: .
      sync:
        manual:
          - src: .
            dest: .
          # - src: 'apps/auth'
          #   dest: .
      custom:
        buildCommand: npx nx run auth:docker-build --conf=development --tag=dev
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p auth
    # TICKETS
    - image: ghcr.io/getlarge/ticketing-tickets
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run tickets:docker-build --conf=development --tag=dev
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p tickets
    # ORDERS
    - image: ghcr.io/getlarge/ticketing-orders
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run orders:docker-build --conf=development --tag=dev
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p orders
    # EXPIRATION
    - image: ghcr.io/getlarge/ticketing-expiration
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run expiration:docker-build --conf=development --tag=dev
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p expiration
    # PAYMENTS
    - image: ghcr.io/getlarge/ticketing-payments
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run payments:docker-build --conf=development --tag=dev
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p payments          
    # CLIENT
    - image: ghcr.io/getlarge/ticketing-client
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run client:docker-build --conf=development --tag=dev --file=apps/client/Dockerfile
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p client
  tagPolicy:
    envTemplate:
      template: dev

---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: deps
deploy:
  kubectl:
    manifests:
      - './infra/k8s/deps/*'

portForward:
  - resourceType: service
    resourceName: auth-mongo-srv
    namespace: default
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: orders-mongo-srv
    namespace: default
    port: 27017
    localPort: 27018
  - resourceType: service
    resourceName: tickets-mongo-srv
    namespace: default
    port: 27017
    localPort: 27019
  - resourceType: service
    resourceName: payments-mongo-srv
    namespace: default
    port: 27017
    localPort: 27020
  - resourceType: service
    resourceName: expiration-redis-srv
    namespace: default
    port: 6379
    localPort: 6379
