apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: apps
deploy:
  kubectl:
    manifests:
      - './infra/k8s/apps/*'
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/getlarge/ticketing-auth
      context: .
      sync:
        manual:
          - src: .
            dest: .
          # - src: 'apps/auth'
          #   dest: .
      custom:
        buildCommand: npx nx run auth:docker-build --conf=production --tag=latest --file=Dockerfile
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p auth
    - image: ghcr.io/getlarge/ticketing-client
      context: .
      sync:
        manual:
          - src: .
            dest: .
      custom:
        buildCommand: npx nx run client:docker-build --conf=production --tag=latest --file=Dockerfile
        dependencies:
          command: node ./tools/nx/get-dependencies-cli.js -p client          
  tagPolicy:
    envTemplate:
      template: latest

---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: deps
deploy:
  kubectl:
    manifests:
      - './infra/k8s/deps/*'
