version: v0.12.0-alpha.0

log:
  level: '##log_level##'

dsn: '##keto_dsn##'

namespaces:
  location: '##namespaces_location##'

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
