apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        # TODO: replace by Jetstream https://blog.ineat-group.com/2021/06/nats-mise-en-pratique-avec-jetstream/
        - name: nats
          image: nats-streaming:0.23
          args:
            [
              --store,
              MEMORY,
              --port,
              '4222',
              --http_port,
              '8222',
              --hb_interval,
              5s,
              --hb_timeout,
              5s,
              --hb_fail_count,
              '2',
              --stan_debug,
              --cluster_id,
              ticketing,
            ]
          resources:
            limits:
              memory: '512Mi'
              cpu: '1000m'

---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
