apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          imagePullPolicy: IfNotPresent
          image: mongo
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mongo --port 27017 --eval "rs.status()" | grep -vq "REMOVED"
            initialDelaySeconds: 45
            timeoutSeconds: 5
          resources:
            limits:
              memory: '256Mi'
              cpu: '150m'

---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
