ARG NODE_VERSION=16.7

FROM node:${NODE_VERSION}-alpine AS builder

ARG APP_NAME=client
ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app

COPY . .
COPY --from=deps /app/node_modules ./node_modules

RUN npx nx build ${APP_NAME} ${BUILD_FLAG}
# RUN yarn build && yarn install --production --ignore-scripts --prefer-offline

# Production image, copy all the files and run next
FROM node:${NODE_VERSION}-alpine AS runner

ARG APP_NAME=client

WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./

COPY --from=builder /apps/${APP_NAME}/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/${APP_NAME}/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node_modules/.bin/next", "start"]