name: 'Checkout and run yarn install'
description: 'This action checks out the commit, sets up Node and installs deps using npm.'
author: 'getlarge'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  fetch-ref:
    required: false
    description: 'Ref to fetch from'
    default: 'refs/heads/main'
  node-version:
    required: true
    description: 'Node version used for setup.'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
outputs:
  cache-hit:
    description: 'Indicates if modules cache was hit.'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout the commit
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.fetch-ref }}
        token: ${{ inputs.token }}

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        echo "CURRENT_NODE_VERSION="node-$(node --version)"" >> $GITHUB_OUTPUT
        echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's,/,-,g')" >> $GITHUB_OUTPUT

    # follow advice in https://gist.github.com/belgattitude/042f9caf10d029badbde6cf9d43e400a
    - name: Cache / restore yarn cache
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: yarn-cache-${{ runner.os }}-${{ steps.yarn-config.outputs.CURRENT_NODE_VERSION }}-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-

    - name: ♻️ Cache / restore yarn install state
      id: yarn-install-state-cache
      uses: actions/cache@v3
      with:
        path: .yarn/ci-cache/
        key: yarn-install-state-cache-${{ runner.os }}-${{ steps.yarn-config.outputs.CURRENT_NODE_VERSION }}-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz
        HUSKY: '0'
        HUSKY_SKIP_INSTALL: 'true'
      run: |
        yarn install --immutable --inline-builds
      shell: bash

    - name: Install dependencies with immutable cache
      if: steps.yarn-cache.outputs.cache-hit == 'true'
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz
        HUSKY: '0'
        HUSKY_SKIP_INSTALL: 'true'
      run: |
        echo "Yarn cache hit - use cache for dependencies installation"
        yarn install --immutable --inline-builds --immutable-cache
      shell: bash
